[pytest]
filterwarnings =
    ignore:distutils Version classes are deprecated.*:DeprecationWarning:pytest_freezegun
    ignore:Inheritance class ClientSession from ClientSession is discouraged:DeprecationWarning:openbb_core.provider.utils.client
    ignore:Using `@model_validator` with mode='after' on a classmethod is deprecated.*:DeprecationWarning:openbb_.*
    ignore:Accessing the 'model_fields' attribute on the instance is deprecated.*:DeprecationWarning:openbb_core.app.model.credentials
