from __future__ import annotations

from typing import Any


HEATMAP_UNIVERSE_VERSION = "us_large_cap_core_2026_05_static_v1"


_HEATMAP_ROWS: tuple[tuple[str, str, str, str, float], ...] = (
    # Technology
    ("MSFT", "Microsoft", "TECHNOLOGY", "SOFTWARE - INFRASTRUCTURE", 8.8),
    ("AAPL", "Apple", "TECHNOLOGY", "CONSUMER ELECTRONICS", 8.7),
    ("NVDA", "NVIDIA", "TECHNOLOGY", "SEMICONDUCTORS", 8.5),
    ("AVGO", "Broadcom", "TECHNOLOGY", "SEMICONDUCTORS", 4.3),
    ("ORCL", "Oracle", "TECHNOLOGY", "SOFTWARE - INFRASTRUCTURE", 2.6),
    ("CRM", "Salesforce", "TECHNOLOGY", "SOFTWARE - APPLICATION", 2.2),
    ("AMD", "AMD", "TECHNOLOGY", "SEMICONDUCTORS", 2.1),
    ("CSCO", "Cisco", "TECHNOLOGY", "COMMUNICATION EQUIPMENT", 1.8),
    ("ACN", "Accenture", "TECHNOLOGY", "INFORMATION TECHNOLOGY SERVICES", 1.7),
    ("IBM", "IBM", "TECHNOLOGY", "INFORMATION TECHNOLOGY SERVICES", 1.6),
    ("INTU", "Intuit", "TECHNOLOGY", "SOFTWARE - APPLICATION", 1.5),
    ("NOW", "ServiceNow", "TECHNOLOGY", "SOFTWARE - APPLICATION", 1.4),
    ("PANW", "Palo Alto Networks", "TECHNOLOGY", "SOFTWARE - INFRASTRUCTURE", 1.3),
    ("PLTR", "Palantir", "TECHNOLOGY", "SOFTWARE - INFRASTRUCTURE", 1.3),
    ("SNPS", "Synopsys", "TECHNOLOGY", "SOFTWARE - INFRASTRUCTURE", 1.2),
    ("CRWD", "CrowdStrike", "TECHNOLOGY", "SOFTWARE - INFRASTRUCTURE", 1.1),
    ("FTNT", "Fortinet", "TECHNOLOGY", "SOFTWARE - INFRASTRUCTURE", 0.9),
    ("ADBE", "Adobe", "TECHNOLOGY", "SOFTWARE - APPLICATION", 1.3),
    ("ADP", "ADP", "TECHNOLOGY", "SOFTWARE - APPLICATION", 1.0),
    ("ROP", "Roper", "TECHNOLOGY", "SOFTWARE - APPLICATION", 0.8),
    ("CDNS", "Cadence", "TECHNOLOGY", "SOFTWARE - APPLICATION", 1.1),
    ("PTC", "PTC", "TECHNOLOGY", "SOFTWARE - APPLICATION", 0.6),
    ("FICO", "Fair Isaac", "TECHNOLOGY", "SOFTWARE - APPLICATION", 0.7),
    ("TXN", "Texas Instruments", "TECHNOLOGY", "SEMICONDUCTORS", 1.4),
    ("QCOM", "Qualcomm", "TECHNOLOGY", "SEMICONDUCTORS", 1.3),
    ("MU", "Micron", "TECHNOLOGY", "SEMICONDUCTORS", 1.1),
    ("ADI", "Analog Devices", "TECHNOLOGY", "SEMICONDUCTORS", 1.0),
    ("AMAT", "Applied Materials", "TECHNOLOGY", "SEMICONDUCTOR EQUIPMENT", 1.3),
    ("LRCX", "Lam Research", "TECHNOLOGY", "SEMICONDUCTOR EQUIPMENT", 1.0),
    ("KLAC", "KLA", "TECHNOLOGY", "SEMICONDUCTOR EQUIPMENT", 0.9),
    ("INTC", "Intel", "TECHNOLOGY", "SEMICONDUCTORS", 0.8),
    ("MCHP", "Microchip", "TECHNOLOGY", "SEMICONDUCTORS", 0.5),
    ("NXPI", "NXP", "TECHNOLOGY", "SEMICONDUCTORS", 0.7),
    ("ANET", "Arista Networks", "TECHNOLOGY", "COMPUTER HARDWARE", 1.0),
    ("DELL", "Dell", "TECHNOLOGY", "COMPUTER HARDWARE", 0.8),
    ("WDC", "Western Digital", "TECHNOLOGY", "COMPUTER HARDWARE", 0.5),
    ("STX", "Seagate", "TECHNOLOGY", "COMPUTER HARDWARE", 0.5),
    # Communication services
    ("GOOGL", "Alphabet", "COMMUNICATION SERVICES", "INTERNET CONTENT & INFORMATION", 7.0),
    ("META", "Meta", "COMMUNICATION SERVICES", "INTERNET CONTENT & INFORMATION", 5.3),
    ("NFLX", "Netflix", "COMMUNICATION SERVICES", "ENTERTAINMENT", 1.6),
    ("DIS", "Disney", "COMMUNICATION SERVICES", "ENTERTAINMENT", 1.0),
    ("TMUS", "T-Mobile", "COMMUNICATION SERVICES", "TELECOM SERVICES", 1.4),
    ("VZ", "Verizon", "COMMUNICATION SERVICES", "TELECOM SERVICES", 0.9),
    ("T", "AT&T", "COMMUNICATION SERVICES", "TELECOM SERVICES", 0.8),
    ("CMCSA", "Comcast", "COMMUNICATION SERVICES", "TELECOM SERVICES", 0.6),
    ("EA", "Electronic Arts", "COMMUNICATION SERVICES", "ELECTRONIC GAMING", 0.5),
    ("TTWO", "Take-Two", "COMMUNICATION SERVICES", "ELECTRONIC GAMING", 0.5),
    ("LYV", "Live Nation", "COMMUNICATION SERVICES", "ENTERTAINMENT", 0.5),
    ("WBD", "Warner Bros. Discovery", "COMMUNICATION SERVICES", "ENTERTAINMENT", 0.4),
    ("CHTR", "Charter", "COMMUNICATION SERVICES", "TELECOM SERVICES", 0.4),
    # Consumer cyclical
    ("AMZN", "Amazon", "CONSUMER CYCLICAL", "INTERNET RETAIL", 6.5),
    ("TSLA", "Tesla", "CONSUMER CYCLICAL", "AUTO MANUFACTURERS", 3.2),
    ("HD", "Home Depot", "CONSUMER CYCLICAL", "HOME IMPROVEMENT", 1.8),
    ("MCD", "McDonald's", "CONSUMER CYCLICAL", "RESTAURANTS", 1.4),
    ("LOW", "Lowe's", "CONSUMER CYCLICAL", "HOME IMPROVEMENT", 1.1),
    ("SBUX", "Starbucks", "CONSUMER CYCLICAL", "RESTAURANTS", 0.8),
    ("BKNG", "Booking", "CONSUMER CYCLICAL", "TRAVEL SERVICES", 1.5),
    ("RCL", "Royal Caribbean", "CONSUMER CYCLICAL", "TRAVEL SERVICES", 0.7),
    ("CCL", "Carnival", "CONSUMER CYCLICAL", "TRAVEL SERVICES", 0.4),
    ("ABNB", "Airbnb", "CONSUMER CYCLICAL", "TRAVEL SERVICES", 0.6),
    ("MAR", "Marriott", "CONSUMER CYCLICAL", "LODGING", 0.7),
    ("HLT", "Hilton", "CONSUMER CYCLICAL", "LODGING", 0.6),
    ("TJX", "TJX", "CONSUMER CYCLICAL", "APPAREL RETAIL", 1.0),
    ("ROST", "Ross Stores", "CONSUMER CYCLICAL", "APPAREL RETAIL", 0.6),
    ("LULU", "Lululemon", "CONSUMER CYCLICAL", "APPAREL RETAIL", 0.5),
    ("NKE", "Nike", "CONSUMER CYCLICAL", "FOOTWEAR & ACCESSORIES", 0.8),
    ("ORLY", "O'Reilly", "CONSUMER CYCLICAL", "AUTO PARTS", 0.8),
    ("AZO", "AutoZone", "CONSUMER CYCLICAL", "AUTO PARTS", 0.7),
    ("GM", "General Motors", "CONSUMER CYCLICAL", "AUTO MANUFACTURERS", 0.5),
    ("F", "Ford", "CONSUMER CYCLICAL", "AUTO MANUFACTURERS", 0.4),
    ("CMG", "Chipotle", "CONSUMER CYCLICAL", "RESTAURANTS", 0.7),
    ("YUM", "Yum Brands", "CONSUMER CYCLICAL", "RESTAURANTS", 0.5),
    ("DRI", "Darden", "CONSUMER CYCLICAL", "RESTAURANTS", 0.4),
    ("EBAY", "eBay", "CONSUMER CYCLICAL", "INTERNET RETAIL", 0.4),
    ("DASH", "DoorDash", "CONSUMER CYCLICAL", "INTERNET RETAIL", 0.6),
    # Consumer defensive
    ("WMT", "Walmart", "CONSUMER DEFENSIVE", "DISCOUNT STORES", 2.4),
    ("COST", "Costco", "CONSUMER DEFENSIVE", "DISCOUNT STORES", 2.0),
    ("PG", "Procter & Gamble", "CONSUMER DEFENSIVE", "HOUSEHOLD & PERSONAL PRODUCTS", 1.8),
    ("KO", "Coca-Cola", "CONSUMER DEFENSIVE", "BEVERAGES - NON-ALCOHOLIC", 1.2),
    ("PEP", "PepsiCo", "CONSUMER DEFENSIVE", "BEVERAGES - NON-ALCOHOLIC", 1.0),
    ("PM", "Philip Morris", "CONSUMER DEFENSIVE", "TOBACCO", 0.9),
    ("MO", "Altria", "CONSUMER DEFENSIVE", "TOBACCO", 0.4),
    ("CL", "Colgate-Palmolive", "CONSUMER DEFENSIVE", "HOUSEHOLD & PERSONAL PRODUCTS", 0.7),
    ("KMB", "Kimberly-Clark", "CONSUMER DEFENSIVE", "HOUSEHOLD & PERSONAL PRODUCTS", 0.5),
    ("MDLZ", "Mondelez", "CONSUMER DEFENSIVE", "CONFECTIONERS", 0.7),
    ("MNST", "Monster Beverage", "CONSUMER DEFENSIVE", "BEVERAGES - NON-ALCOHOLIC", 0.5),
    ("KDP", "Keurig Dr Pepper", "CONSUMER DEFENSIVE", "BEVERAGES - NON-ALCOHOLIC", 0.4),
    ("EL", "Estee Lauder", "CONSUMER DEFENSIVE", "HOUSEHOLD & PERSONAL PRODUCTS", 0.3),
    ("TGT", "Target", "CONSUMER DEFENSIVE", "DISCOUNT STORES", 0.5),
    ("DG", "Dollar General", "CONSUMER DEFENSIVE", "DISCOUNT STORES", 0.3),
    ("KR", "Kroger", "CONSUMER DEFENSIVE", "GROCERY STORES", 0.4),
    ("ADM", "Archer-Daniels-Midland", "CONSUMER DEFENSIVE", "FARM PRODUCTS", 0.4),
    ("GIS", "General Mills", "CONSUMER DEFENSIVE", "PACKAGED FOODS", 0.4),
    ("HSY", "Hershey", "CONSUMER DEFENSIVE", "CONFECTIONERS", 0.3),
    ("SYY", "Sysco", "CONSUMER DEFENSIVE", "FOOD DISTRIBUTION", 0.4),
    ("KHC", "Kraft Heinz", "CONSUMER DEFENSIVE", "PACKAGED FOODS", 0.3),
    ("STZ", "Constellation Brands", "CONSUMER DEFENSIVE", "BEVERAGES - WINERIES", 0.4),
    # Financial
    ("BRK-B", "Berkshire", "FINANCIAL", "INSURANCE - DIVERSIFIED", 4.5),
    ("JPM", "JPMorgan", "FINANCIAL", "BANKS - DIVERSIFIED", 2.4),
    ("V", "Visa", "FINANCIAL", "CREDIT SERVICES", 2.0),
    ("MA", "Mastercard", "FINANCIAL", "CREDIT SERVICES", 1.7),
    ("BAC", "Bank of America", "FINANCIAL", "BANKS - DIVERSIFIED", 1.1),
    ("WFC", "Wells Fargo", "FINANCIAL", "BANKS - DIVERSIFIED", 0.9),
    ("C", "Citigroup", "FINANCIAL", "BANKS - DIVERSIFIED", 0.7),
    ("AXP", "American Express", "FINANCIAL", "CREDIT SERVICES", 0.9),
    ("GS", "Goldman Sachs", "FINANCIAL", "CAPITAL MARKETS", 0.8),
    ("MS", "Morgan Stanley", "FINANCIAL", "CAPITAL MARKETS", 0.8),
    ("BLK", "BlackRock", "FINANCIAL", "ASSET MANAGEMENT", 0.8),
    ("SCHW", "Charles Schwab", "FINANCIAL", "CAPITAL MARKETS", 0.7),
    ("SPGI", "S&P Global", "FINANCIAL", "FINANCIAL DATA & EXCHANGES", 0.8),
    ("ICE", "Intercontinental Exchange", "FINANCIAL", "FINANCIAL DATA & EXCHANGES", 0.7),
    ("CME", "CME Group", "FINANCIAL", "FINANCIAL DATA & EXCHANGES", 0.7),
    ("COF", "Capital One", "FINANCIAL", "CREDIT SERVICES", 0.5),
    ("USB", "U.S. Bancorp", "FINANCIAL", "BANKS - REGIONAL", 0.4),
    ("PNC", "PNC", "FINANCIAL", "BANKS - REGIONAL", 0.5),
    ("TFC", "Truist", "FINANCIAL", "BANKS - REGIONAL", 0.3),
    ("CB", "Chubb", "FINANCIAL", "INSURANCE - PROPERTY", 0.7),
    ("PGR", "Progressive", "FINANCIAL", "INSURANCE - PROPERTY", 0.8),
    ("TRV", "Travelers", "FINANCIAL", "INSURANCE - PROPERTY", 0.4),
    ("AON", "Aon", "FINANCIAL", "INSURANCE BROKERS", 0.6),
    ("AFL", "Aflac", "FINANCIAL", "INSURANCE", 0.4),
    ("MMC", "Marsh & McLennan", "FINANCIAL", "INSURANCE BROKERS", 0.7),
    ("AJG", "Arthur J. Gallagher", "FINANCIAL", "INSURANCE BROKERS", 0.5),
    ("ALL", "Allstate", "FINANCIAL", "INSURANCE - PROPERTY", 0.4),
    ("KKR", "KKR", "FINANCIAL", "ASSET MANAGEMENT", 0.6),
    ("BX", "Blackstone", "FINANCIAL", "ASSET MANAGEMENT", 0.7),
    # Healthcare
    ("LLY", "Eli Lilly", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 3.2),
    ("JNJ", "Johnson & Johnson", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 1.7),
    ("UNH", "UnitedHealth", "HEALTHCARE", "HEALTHCARE PLANS", 1.8),
    ("ABBV", "AbbVie", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 1.2),
    ("MRK", "Merck", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 1.2),
    ("TMO", "Thermo Fisher", "HEALTHCARE", "DIAGNOSTICS & RESEARCH", 1.0),
    ("ABT", "Abbott", "HEALTHCARE", "MEDICAL DEVICES", 1.0),
    ("ISRG", "Intuitive Surgical", "HEALTHCARE", "MEDICAL DEVICES", 0.9),
    ("DHR", "Danaher", "HEALTHCARE", "DIAGNOSTICS & RESEARCH", 0.8),
    ("PFE", "Pfizer", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 0.7),
    ("AMGN", "Amgen", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 0.8),
    ("MDT", "Medtronic", "HEALTHCARE", "MEDICAL DEVICES", 0.7),
    ("BSX", "Boston Scientific", "HEALTHCARE", "MEDICAL DEVICES", 0.7),
    ("SYK", "Stryker", "HEALTHCARE", "MEDICAL DEVICES", 0.8),
    ("CVS", "CVS Health", "HEALTHCARE", "HEALTHCARE PLANS", 0.5),
    ("CI", "Cigna", "HEALTHCARE", "HEALTHCARE PLANS", 0.6),
    ("HUM", "Humana", "HEALTHCARE", "HEALTHCARE PLANS", 0.4),
    ("BMY", "Bristol Myers", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 0.5),
    ("GILD", "Gilead", "HEALTHCARE", "DRUG MANUFACTURERS - GENERAL", 0.6),
    ("REGN", "Regeneron", "HEALTHCARE", "BIOTECHNOLOGY", 0.6),
    ("VRTX", "Vertex", "HEALTHCARE", "BIOTECHNOLOGY", 0.6),
    ("MCK", "McKesson", "HEALTHCARE", "MEDICAL DISTRIBUTION", 0.7),
    ("COR", "Cencora", "HEALTHCARE", "MEDICAL DISTRIBUTION", 0.5),
    ("HCA", "HCA Healthcare", "HEALTHCARE", "MEDICAL CARE", 0.6),
    ("ELV", "Elevance", "HEALTHCARE", "HEALTHCARE PLANS", 0.6),
    ("BDX", "Becton Dickinson", "HEALTHCARE", "MEDICAL INSTRUMENTS", 0.5),
    ("EW", "Edwards Lifesciences", "HEALTHCARE", "MEDICAL DEVICES", 0.5),
    ("IQV", "IQVIA", "HEALTHCARE", "DIAGNOSTICS & RESEARCH", 0.4),
    ("ZTS", "Zoetis", "HEALTHCARE", "DRUG MANUFACTURERS - SPECIALTY", 0.4),
    # Industrials
    ("GE", "GE Aerospace", "INDUSTRIALS", "AEROSPACE & DEFENSE", 1.2),
    ("RTX", "RTX", "INDUSTRIALS", "AEROSPACE & DEFENSE", 1.1),
    ("CAT", "Caterpillar", "INDUSTRIALS", "FARM & HEAVY CONSTRUCTION", 1.0),
    ("DE", "Deere", "INDUSTRIALS", "FARM & HEAVY CONSTRUCTION", 0.9),
    ("BA", "Boeing", "INDUSTRIALS", "AEROSPACE & DEFENSE", 0.8),
    ("LMT", "Lockheed Martin", "INDUSTRIALS", "AEROSPACE & DEFENSE", 0.8),
    ("HON", "Honeywell", "INDUSTRIALS", "CONGLOMERATES", 0.9),
    ("UPS", "UPS", "INDUSTRIALS", "INTEGRATED FREIGHT", 0.6),
    ("ETN", "Eaton", "INDUSTRIALS", "SPECIALTY INDUSTRIAL MACHINERY", 1.0),
    ("PH", "Parker-Hannifin", "INDUSTRIALS", "SPECIALTY INDUSTRIAL MACHINERY", 0.8),
    ("MMM", "3M", "INDUSTRIALS", "CONGLOMERATES", 0.4),
    ("UNP", "Union Pacific", "INDUSTRIALS", "RAILROADS", 0.8),
    ("CSX", "CSX", "INDUSTRIALS", "RAILROADS", 0.5),
    ("NSC", "Norfolk Southern", "INDUSTRIALS", "RAILROADS", 0.4),
    ("WM", "Waste Management", "INDUSTRIALS", "WASTE MANAGEMENT", 0.7),
    ("RSG", "Republic Services", "INDUSTRIALS", "WASTE MANAGEMENT", 0.5),
    ("ITW", "Illinois Tool Works", "INDUSTRIALS", "SPECIALTY INDUSTRIAL MACHINERY", 0.6),
    ("EMR", "Emerson", "INDUSTRIALS", "SPECIALTY INDUSTRIAL MACHINERY", 0.5),
    ("PCAR", "PACCAR", "INDUSTRIALS", "FARM & HEAVY CONSTRUCTION", 0.5),
    ("CMI", "Cummins", "INDUSTRIALS", "SPECIALTY INDUSTRIAL MACHINERY", 0.4),
    ("FDX", "FedEx", "INDUSTRIALS", "INTEGRATED FREIGHT", 0.5),
    ("JCI", "Johnson Controls", "INDUSTRIALS", "BUILDING PRODUCTS", 0.4),
    ("TT", "Trane", "INDUSTRIALS", "BUILDING PRODUCTS", 0.6),
    ("AXON", "Axon", "INDUSTRIALS", "AEROSPACE & DEFENSE", 0.4),
    ("GEV", "GE Vernova", "INDUSTRIALS", "SPECIALTY INDUSTRIAL MACHINERY", 0.5),
    ("CARR", "Carrier", "INDUSTRIALS", "BUILDING PRODUCTS", 0.4),
    # Energy
    ("XOM", "Exxon Mobil", "ENERGY", "OIL & GAS INTEGRATED", 1.7),
    ("CVX", "Chevron", "ENERGY", "OIL & GAS INTEGRATED", 1.0),
    ("COP", "ConocoPhillips", "ENERGY", "OIL & GAS E&P", 0.7),
    ("EOG", "EOG Resources", "ENERGY", "OIL & GAS E&P", 0.5),
    ("SLB", "SLB", "ENERGY", "OIL & GAS EQUIPMENT", 0.5),
    ("OXY", "Occidental", "ENERGY", "OIL & GAS E&P", 0.4),
    ("MPC", "Marathon Petroleum", "ENERGY", "OIL & GAS REFINING", 0.4),
    ("PSX", "Phillips 66", "ENERGY", "OIL & GAS REFINING", 0.4),
    ("VLO", "Valero", "ENERGY", "OIL & GAS REFINING", 0.4),
    ("KMI", "Kinder Morgan", "ENERGY", "OIL & GAS MIDSTREAM", 0.4),
    ("WMB", "Williams", "ENERGY", "OIL & GAS MIDSTREAM", 0.4),
    ("HAL", "Halliburton", "ENERGY", "OIL & GAS EQUIPMENT", 0.3),
    ("BKR", "Baker Hughes", "ENERGY", "OIL & GAS EQUIPMENT", 0.3),
    ("FANG", "Diamondback", "ENERGY", "OIL & GAS E&P", 0.4),
    ("OKE", "ONEOK", "ENERGY", "OIL & GAS MIDSTREAM", 0.4),
    ("DVN", "Devon Energy", "ENERGY", "OIL & GAS E&P", 0.3),
    ("CTRA", "Coterra", "ENERGY", "OIL & GAS E&P", 0.3),
    # Utilities
    ("NEE", "NextEra Energy", "UTILITIES", "UTILITIES - REGULATED", 0.8),
    ("SO", "Southern", "UTILITIES", "UTILITIES - REGULATED", 0.5),
    ("DUK", "Duke Energy", "UTILITIES", "UTILITIES - REGULATED", 0.5),
    ("AEP", "AEP", "UTILITIES", "UTILITIES - REGULATED", 0.4),
    ("EXC", "Exelon", "UTILITIES", "UTILITIES - REGULATED", 0.4),
    ("XEL", "Xcel Energy", "UTILITIES", "UTILITIES - REGULATED", 0.3),
    ("SRE", "Sempra", "UTILITIES", "UTILITIES - REGULATED", 0.4),
    ("PEG", "Public Service Enterprise", "UTILITIES", "UTILITIES - REGULATED", 0.3),
    ("ED", "Con Edison", "UTILITIES", "UTILITIES - REGULATED", 0.3),
    ("D", "Dominion", "UTILITIES", "UTILITIES - REGULATED", 0.3),
    ("EIX", "Edison International", "UTILITIES", "UTILITIES - REGULATED", 0.3),
    ("PCG", "PG&E", "UTILITIES", "UTILITIES - REGULATED", 0.3),
    ("CEG", "Constellation Energy", "UTILITIES", "UTILITIES - RENEWABLE", 0.5),
    # Real estate
    ("PLD", "Prologis", "REAL ESTATE", "REIT - INDUSTRIAL", 0.8),
    ("AMT", "American Tower", "REAL ESTATE", "REIT - SPECIALTY", 0.7),
    ("EQIX", "Equinix", "REAL ESTATE", "REIT - SPECIALTY", 0.8),
    ("WELL", "Welltower", "REAL ESTATE", "REIT - HEALTHCARE", 0.5),
    ("SPG", "Simon Property", "REAL ESTATE", "REIT - RETAIL", 0.4),
    ("PSA", "Public Storage", "REAL ESTATE", "REIT - INDUSTRIAL", 0.5),
    ("O", "Realty Income", "REAL ESTATE", "REIT - RETAIL", 0.3),
    ("DLR", "Digital Realty", "REAL ESTATE", "REIT - SPECIALTY", 0.4),
    ("CCI", "Crown Castle", "REAL ESTATE", "REIT - SPECIALTY", 0.3),
    ("IRM", "Iron Mountain", "REAL ESTATE", "REIT - SPECIALTY", 0.4),
    ("VICI", "VICI Properties", "REAL ESTATE", "REIT - RETAIL", 0.3),
    ("EXR", "Extra Space Storage", "REAL ESTATE", "REIT - INDUSTRIAL", 0.3),
    # Basic materials
    ("LIN", "Linde", "BASIC MATERIALS", "SPECIALTY CHEMICALS", 1.1),
    ("SHW", "Sherwin-Williams", "BASIC MATERIALS", "SPECIALTY CHEMICALS", 0.7),
    ("APD", "Air Products", "BASIC MATERIALS", "SPECIALTY CHEMICALS", 0.5),
    ("ECL", "Ecolab", "BASIC MATERIALS", "SPECIALTY CHEMICALS", 0.5),
    ("NEM", "Newmont", "BASIC MATERIALS", "GOLD", 0.4),
    ("FCX", "Freeport-McMoRan", "BASIC MATERIALS", "COPPER", 0.4),
    ("NUE", "Nucor", "BASIC MATERIALS", "STEEL", 0.4),
    ("DD", "DuPont", "BASIC MATERIALS", "SPECIALTY CHEMICALS", 0.3),
    ("DOW", "Dow", "BASIC MATERIALS", "CHEMICALS", 0.3),
    ("MLM", "Martin Marietta", "BASIC MATERIALS", "BUILDING MATERIALS", 0.4),
    ("VMC", "Vulcan Materials", "BASIC MATERIALS", "BUILDING MATERIALS", 0.4),
    ("PPG", "PPG", "BASIC MATERIALS", "SPECIALTY CHEMICALS", 0.3),
    ("STLD", "Steel Dynamics", "BASIC MATERIALS", "STEEL", 0.3),
    ("CTVA", "Corteva", "BASIC MATERIALS", "AGRICULTURAL INPUTS", 0.3),
)


def _entry(row: tuple[str, str, str, str, float]) -> dict[str, Any]:
    symbol, label, sector, industry, weight = row
    return {
        "symbol": symbol,
        "label": label,
        "sector": sector,
        "industry": industry,
        "weight": weight,
    }


US_EQUITY_HEATMAP_UNIVERSE: tuple[dict[str, Any], ...] = tuple(
    _entry(row) for row in _HEATMAP_ROWS
)
