from abc import ABC, abstractmethod
from pydantic import BaseModel, Field
from typing import List

class RiskEvaluationResult(BaseModel):
    bull_points: List[str] = Field(default_factory=list, description="Extracted positive factors or catalysts.")
    bear_points: List[str] = Field(default_factory=list, description="Extracted negative factors or risks.")

class BaseRiskEngine(ABC):
    @abstractmethod
    async def evaluate_risk(self, raw_output: dict) -> RiskEvaluationResult:
        """
        Takes the raw dictionary generated by the inference model, and
        parses/extracts a structured RiskEvaluationResult.
        
        [ENGINEERING GUARDRAIL]:
        Concrete implementations of this interface must NEVER block the FastAPI event loop.
        If your implementation performs heavy synchronous computation (like loading PyTorch weights),
        you MUST internally wrap that logic inside `asyncio.to_thread` or an equivalent offloader.
        """
        pass
